name: Run Hello World Container

on:
  push:
    branches:
      - main  # Executa sempre que houver um push na branch main

jobs:
  run-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Docker
        uses: docker/setup-buildx-action@v3

      - name: Rodar container hello-world
        run: |
          docker run hello-world
